### ISSUE TITLE
No products added to the feed - V13.0.0 Umbraco 13.3.0

### ISSUE THREAD

**Issue by ipsisPuckHolshuijsen** [umbraco/Umbraco.Commerce.ProductFeeds#16]
Hi,

I added the 13.0.0 version to my Umbraco 13.3.0 version website, set it up according to the documentation, but I get no products inside my feed. I can't find any logs about what might be the problem.

This is the feed it produces:
![image](https://github.com/user-attachments/assets/f93039a1-8129-4acc-a9be-71269f4e45fc)

As you can see, there is a feed, but no products shows up0.
I've set up the feed like this:
![image](https://github.com/user-attachments/assets/65f13f03-f081-48a9-abad-561f7a6fe07d)

And the fields mapping like this:
![image](https://github.com/user-attachments/assets/d0931a89-2765-42e1-8276-75d0e8a722f7)

The only weird thing I see is the way the product doctypes are selected. According to the documentation, this way of selecting should be from version 14.0.0.

Thanks in advance

**Comment by umbracotrd** [comment]
Hi, everything looks pretty standard to me. There's nothing wrong with the document type picker. You can see the document type picker works as in the [demo here](https://photos.google.com/share/AF1QipMNAVnZ3273BdAnyaLXotXEFohxvlikWHwOWDCEODt2rLbUYquD6y72PafgbHSZZg/photo/AF1QipMA4bQ37ibkZox32F_AZwLjIcpAKOLAtCsL7_YM?key=cEtFZ0dkM3RBN01iX1g4c0lTYTZLSGxVM2k3SU1n)

Because you can see the feed and there're no logs at error level, I think your basic settings is correct. It's just that the plugin can not find any product with the product document types and the product root you provided. The logic to query the product can be found [here](https://github.com/umbraco/Umbraco.Commerce.ProductFeeds/blob/b8afb7ed259d8caaf8557b7cc49d9b8752820e41/src/Umbraco.Commerce.ProductFeeds.Core/Features/ProductQueries/Implementations/ProductQueryService.cs#L28).

Can you show me how you're construct your product tree? I assume it looks like this: Home page > Producten > Product Variant.

One more thing, can you verify your data in the database using this query? `select * from umbracoCommerceProductFeedSetting`
The result should be similar to this without the last column `includeTaxInPrice` which is added in `v13.1.0`
```
97B054C0-EBF5-4F24-BE0A-76D52A2F2046	GoogleMerchantCenter	all	all		multiVariantProductPage;productPage	NULL	9359686D-143C-4CA9-8A76-5CF836198E90	C23CC1CA-37CA-4A70-A9D8-018BFF89D4F2	[{"PropertyAlias":"sku","NodeName":"g:id","ValueExtractorName":"DefaultSingleValuePropertyExtractor"},{"PropertyAlias":"Name","NodeName":"g:title","ValueExtractorName":"DefaultSingleValuePropertyExtractor"},{"PropertyAlias":"stock","NodeName":"g:availability","ValueExtractorName":"DefaultGoogleAvailabilityValueExtractor"},{"PropertyAlias":"image","NodeName":"g:image_link","ValueExtractorName":"DefaultMediaPickerPropertyValueExtractor"},{"PropertyAlias":"images","NodeName":"g:image_link","ValueExtractorName":"DefaultMultipleMediaPickerPropertyValueExtractor"}]	1
30964984-1C5D-47C4-9DD3-C176E8AAD178	GoogleMerchantCenter	multivariant	multiple variants		multiVariantProductPage	NULL	A8BCC42F-88A2-427D-8FCC-2DE3ED457E57	C23CC1CA-37CA-4A70-A9D8-018BFF89D4F2	[{"PropertyAlias":"sku","NodeName":"g:id","ValueExtractorName":"DefaultSingleValuePropertyExtractor"},{"PropertyAlias":"Name","NodeName":"g:title","ValueExtractorName":"DefaultSingleValuePropertyExtractor"},{"PropertyAlias":"stock","NodeName":"g:availability","ValueExtractorName":"DefaultGoogleAvailabilityValueExtractor"},{"PropertyAlias":"image","NodeName":"g:image_link","ValueExtractorName":"DefaultMediaPickerPropertyValueExtractor"},{"PropertyAlias":"images","NodeName":"g:image_link","ValueExtractorName":"DefaultMultipleMediaPickerPropertyValueExtractor"}]	1
```

**Comment by ipsisPuckHolshuijsen** [comment]
Hi,

Thanks for the answer.
I can verify that the data in the database looks like that :) updated productfeeds to v13.1.0 yesterday, hoping it would solve the issue (it didn't).
`id	feedType	feedRelativePath	feedName	feedDescription	productDocumentTypeAliases	productChildVariantTypeAlias	productRootKey	storeId	productPropertyNameMappings	includeTaxInPrice
0CDB8BA6-A5B8-44F0-A6B7-5919F74BC86C	GoogleMerchantCenter	testfeed	Google-feed	All products	dtProduct	productVariant	BA06B275-82FD-406E-853E-B70502351188	D31183CC-67A7-4591-890F-018EA41D92DB	[{"PropertyAlias":"sku","NodeName":"g:id","ValueExtractorName":"DefaultSingleValuePropertyExtractor"},{"PropertyAlias":"stock","NodeName":"g:availability","ValueExtractorName":"DefaultGoogleAvailabilityValueExtractor"},{"PropertyAlias":"Title","NodeName":"g:title","ValueExtractorName":"DefaultSingleValuePropertyExtractor"},{"PropertyAlias":"PageImage","NodeName":"g:image_link","ValueExtractorName":"DefaultMediaPickerPropertyValueExtractor"},{"PropertyAlias":"PageImages","NodeName":"g:image_link","ValueExtractorName":"DefaultMultipleMediaPickerPropertyValueExtractor"},{"PropertyAlias":"price","NodeName":"g:price","ValueExtractorName":"DefaultSingleValuePropertyExtractor"}]	1
FAEB2578-A5D6-4C3C-B7D6-26D94EA420DA	GoogleMerchantCenter	testfeed-testproducten	testfeed-testproducten		dtProduct	productVariant	DEB41998-232A-4360-9A2B-CDC04697C2C5	D31183CC-67A7-4591-890F-018EA41D92DB	[{"PropertyAlias":"sku","NodeName":"g:id","ValueExtractorName":"DefaultSingleValuePropertyExtractor"},{"PropertyAlias":"Title","NodeName":"g:title","ValueExtractorName":"DefaultSingleValuePropertyExtractor"},{"PropertyAlias":"PageImage","NodeName":"g:image_link","ValueExtractorName":"DefaultMediaPickerPropertyValueExtractor"},{"PropertyAlias":"PageImages","NodeName":"g:image_link","ValueExtractorName":"DefaultMultipleMediaPickerPropertyValueExtractor"}]	1`

Here's a screenshot of what the tree looks like:
![image](https://github.com/user-attachments/assets/1ec0f6cc-84df-429d-98eb-cf973abef94e)

Those 3 products are of the type dtProduct and have multivariants underneath them of the documenttype productVariant
![image](https://github.com/user-attachments/assets/3b4662ab-5a01-4a02-83ec-077fb8c53d58)

I was looking inside the external index (and i could find those products). I will try to locally reproduce the query to see if there is something weird going on at my side.
