### ISSUE TITLE
Only 500 products returning

### ISSUE THREAD

**Issue by timgaunt** [umbraco/Umbraco.Commerce.ProductFeeds#18]
We have a large catalog with several thousand products in but only the first `499` items are showing in the feed.

I've not tested it but I suspect the issue is that you're limited by Lucene's Safe Take here: https://github.com/umbraco/Umbraco.Commerce.ProductFeeds/blob/main/src/Umbraco.Commerce.ProductFeeds.Core/Features/ProductQueries/Implementations/ProductQueryService.cs#L59

This defaults to `500` which you can override like this: `.Execute(QueryOptions.SkipTake(0, 100000))`

We're running `13.1.0` but looking at that code it would appear that it's an issue in the current version as well.

**Comment by timgaunt** [comment]
I've created a PR - https://github.com/umbraco/Umbraco.Commerce.ProductFeeds/pull/19

**Comment by umbracotrd** [comment]
It's true that Examine returns 500 items by default https://github.com/Shazwazza/Examine/issues/376
I've pushed `13.1.1` and `14.1.1` which include your fix.

Thank you for submitting a PR.
