### ISSUE TITLE
Adjustments to settings

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Commerce.ProductFeeds#2]
Since discussions are not available, I will add some feedback in an issue instead.

I think document type selection should be a picker instead and probably not include media types. Any specific reason it need to store aliases and not just udis from document type picker?

Furthermore the product root can be a picker as well.

![image](https://github.com/umbraco/Umbraco.Commerce.ProductFeeds/assets/2919859/9fc9a047-d997-47b8-a3bb-c142276a60b4)

**Comment by mattbrailsford** [comment]
Hey @bjarnef 

You’re a little bit early. This add on is still going through internal review where this has already been highlighted. 

You might want to wait till it’s officially released to review further. 

I appreciate you taking the time to try it out though 👍🏻
