### ISSUE TITLE
Facebook rejecting feed as it's all on a single line

### ISSUE THREAD

**Issue by timgaunt** [umbraco/Umbraco.Commerce.ProductFeeds#20]
This is a new one on me but it would appear that Facebook likes the XML to be formatted rather than on a single line:

![image](https://github.com/user-attachments/assets/1becf69b-1968-4193-8bb4-ed5c1c2563a3)

> Feed failed to upload
> This file contains a line or row of text that exceeds our size limit of 5242880 bytes or characters. If you use an XML, please format it into multiple lines with one field per line. If you use a CSV or TSV, please shorten any rows that exceed this limit (which could be due to fields with long URLs).

**Comment by timgaunt** [comment]
I've popped a fix in a PR here: https://github.com/umbraco/Umbraco.Commerce.ProductFeeds/pull/21

![image](https://github.com/user-attachments/assets/862ae2c8-a115-4b48-8bbb-1b2ed3a2a528)

**Comment by umbracotrd** [comment]
Thanks for the PR @timgaunt , I've pushed the `13.1.2--preview.1+11cdd70` to the Umbraco nightly feed. If you don't find any issue with it then I'll push the `13.1.2` to nuget tomorrow.

The only potential issue I can think of is the formatted xml file size will be bigger than the one-liner version.
