### ISSUE TITLE
AddCommerceProductFeeds extension on `IUmbracoCommerceBuilder`

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Commerce.ProductFeeds#3]
I noticed `AddCommerceProductFeeds` is an extension on `IUmbracoBuilder` - any reason it isn't an extension of `IUmbracoCommerceBuilder` instead?
https://github.com/umbraco/Umbraco.Commerce.ProductFeeds/blob/main/src/Umbraco.Commerce.ProductFeeds/Initializations/ServiceCollectionExtensions.cs#L23

**Comment by mattbrailsford** [comment]
Hey @bjarnef 

You’re a little bit early. This add on is still going through internal review where this has already been highlighted. 

You might want to wait till it’s officially released to review further. 

I appreciate you taking the time to try it out though 👍🏻
