### ISSUE TITLE
Google Merchant Feed, incorrect price format

### ISSUE THREAD

**Issue by BenWhite27** [umbraco/Umbraco.Commerce.ProductFeeds#7]
Looking at the code and generated feed, it appears that the `g:price` xml content is formatted with a currency symbol.  Looking at the google documentation it appears this should be formatted with an ISO 4217 currency code suffix, without a currency symbol.
https://support.google.com/merchants/answer/6324371?hl=en-GB

Current formatting
```
<g:price>£15.00</g:price>
```

Expected formatting
```
<g:price>15.00 GBP</g:price>
```

The actual merchant center reports an issue with the product after the feed has processed.
![image](https://github.com/umbraco/Umbraco.Commerce.ProductFeeds/assets/7678016/3a5f5e3a-1c81-4055-bcc7-283227953b5d)

**Comment by umbracotrd** [comment]
The price formatting issue was fixed in #8 and a toggle was added in `v13.1.0` and `v14.1.0` to decide whether or not to add the tax to product price in the feed.
